name: 'Build'

on:
  pull_request:
  push:
    branches:
      - 'master'
  workflow_dispatch:

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=true -Dorg.gradle.parallel=true -Dorg.gradle.welcome=never
  GPG_SEC: ${{ secrets.PGP_SEC }}
  GPG_PASSWORD: ${{ secrets.PGP_PASSWORD }}

jobs:
  build-native:
    name: 'Build native code'
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Report tool versions
        run: |
          echo "OS: $(uname -a)"
          echo "Architecture: $(arch)"
          echo "GCC version: $(gcc --version | head -n1)"
          echo "GCC target architecture: $(gcc -dumpmachine)"
          echo "Clang version: $(clang --version)"
          echo "Clang target architecture: $(clang -dumpmachine)"
          echo "CMake version: $(cmake --version | head -n1)"
        shell: bash
